captcha:
  img-height: 80
  img-width: 240
  key-long: 6
casbin:
  model-path: ./resource/rbac_model.conf
email:
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  nickname: test
  port: 465
  secret: xxx
  to: xxx@qq.com
jwt:
  signing-key: qmPlus
  expires-time: 604800
  buffer-time: 86400
mongodb:
  db: NodePress
  addr: mongodb://localhost:27017
  password: ""
  number: 10
mysql:
  path: 127.0.0.1:3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: nice
  username: root
  password: "123456"
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: public
  addr: 8088
  db-type: mysql
  oss-type: local
  use-multipoint: false
  db_migrate: false
timer:
  start: true
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
zap:
  level: info
  format: console
  prefix: '[NICE]'
  director: log
  linkname: ""
  showline: false
  encodelevel: ""
  stacktracekey: ""
  loginconsole: false
