captcha:
  img-height: 80
  img-width: 240
  key-long: 6
casbin:
  model-path: ./resource/rbac_model.conf
email:
  host: smtp.163.com
  port: 465
  user: ""
  pass: ""
  to: xxx@qq.com
jwt:
  signing-key: qmPlus
  expires-time: 604800
  buffer-time: 86400
mongodb:
  db: NodePress
  addr: mongodb://172.16.4.145:27017
  password: ""
  number: 10
mysql:
  read:
    path: 127.0.0.1:3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: nice
    username: root
    password: "123456"
  write:
    path: 127.0.0.1:3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db-name: nice
    username: root
    password: "123456"
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
  maxretries: 0
  poolsize: 0
  minidleconns: 0
system:
  env: dev
  port: 8000
  domain: http://127.0.0.1
  db-type: mysql
  oss-type: local
  use-multipoint: false
  db_migrate: false
  language: zh-cn
timer:
  start: true
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
zap:
  level: info
  format: console
  prefix: '[NICE]'
  director: log
  linkname: ""
  showline: false
  encodelevel: ""
  stacktracekey: ""
  loginconsole: false
