basePath: /
definitions:
  request.Login:
    properties:
      uk:
        description: 用户 账号密码
        type: string
    type: object
info:
  contact:
    email: linyj@163.com
    name: linyj
    url: http://localhost:8080/swagger/index.html
  description: This is a sample Server pets
  title: Swagger Example API
  version: 0.0.1
paths:
  /base/login:
    post:
      parameters:
      - description: 用户名, 密码, 验证码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"登陆成功"}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - Base
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
